// List: get selected row
// Replace yourField with fieldName
const context = oEvent.oSource.getBindingContext();

// Get entire model
const data = context.getObject();

modelFormDepartmentDetails.setData(data);

modelinFormDepartmentDetailsdepartment_status.setData(await apiGET_Status());

inFormDepartmentDetailsdepartment_status.setSelectedKey(data.department_status);

FormDepartmentDetails.setVisible(true);

NavContainer.to(PageDepartmentDetails);